#!/bin/bash

mvn site:stage
git checkout gh-pages

cp -R target/staging/* .
git add fluvius-core
git add fluvius-json
git add fluvius-api
git add fluvius-test
git add *.html
git add js
git add css
git add img
git add images
git add fonts
git add checkstyle.rss
git commit -m "Update site"
